### ISSUE TITLE
Animal Controller: GetById not working

### ISSUE THREAD

**Issue by Strypper** [Strypper/PetaVerseApi#20]
AnimalController
```
[HttpGet("{animalId}")]
public async Task<IActionResult> GetById(int animalId, CancellationToken cancellationToken = default)
{
    var animal = await _animalRepository.FindByIdAsync(animalId, cancellationToken);
    return animal != null ? Ok(_mapper.Map<Animal>(animal)) : NotFound("Unable to find the requested animal"); 
}
```
Error:

> System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Species.Animals.Species.Animals.Species.Animals.Species.Animals.Species.Animals.Species.Animals.Species.Animals.Species.Animals.Species.Animals.Species.Animals.Species.Name.

**Comment by Strypper** [comment]
@E-vaTRON Need to have a look at this

**Comment by E-vaTRON** [comment]
[HttpGet("{animalId}")]
public async Task<IActionResult> GetById(int animalId, CancellationToken cancellationToken = default)
{
    var animal = await _animalRepository.FindByIdAsync(animalId, cancellationToken);
    return animal != null ? Ok(_mapper.Map<AnimalDTO>(animal)) : NotFound("Unable to find the requested animal"); 
}

**Comment by E-vaTRON** [comment]
_mapper.Map<Animal>(animal) to _mapper.Map<AnimalDTO>(animal)

**Comment by E-vaTRON** [comment]
return map form Animal to AnimalDTO

**Comment by ValentinMozesMatias** [comment]
Regarding:

"System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32."

It might also be a problem from building services in Program.cs

If you are using .NetCore 6+ then there would be a solution to place the below statement in the Program.cs Class:

builder.Services.AddControllers().AddJsonOptions(x =>
                x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles);

If you are using .NetCore 5:

services.AddControllers().AddJsonOptions(x =>
   x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve);

If you are using .NetCore 3.1 or less then you need to install  Microsoft.AspNetCore.Mvc.NewtonsoftJson with the library that coresponds to your version of .NetCore then configure services:

services.AddControllers().AddNewtonsoftJson(x => 
 x.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);


Hope this helps.
Valentin.

**Comment by Strypper** [comment]
> Regarding:
> 
> "System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32."
> 
> It might also be a problem from building services in Program.cs
> 
> If you are using .NetCore 6+ then there would be a solution to place the below statement in the Program.cs Class:
> 
> builder.Services.AddControllers().AddJsonOptions(x => x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles);
> 
> If you are using .NetCore 5:
> 
> services.AddControllers().AddJsonOptions(x => x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve);
> 
> If you are using .NetCore 3.1 or less then you need to install Microsoft.AspNetCore.Mvc.NewtonsoftJson with the library that coresponds to your version of .NetCore then configure services:
> 
> services.AddControllers().AddNewtonsoftJson(x => x.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);
> 
> Hope this helps. Valentin.

Thanks Valentin the problem is that we return the original type from the mapper this make the mapping process stuck with the recursive
